import ContentLoader from 'react-content-loader';
import style from './Loader.module.scss';

const ProductInfoPageLoader = () => {
  return (
    <div className={style.loader}>
      <div className={style['loader--desktop']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 1135 957"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="624"
            y="295"
            rx="16"
            ry="16"
            width="320"
            height="32"
          />
          <rect
            x="624"
            y="192"
            rx="16"
            ry="16"
            width="320"
            height="32"
          />
          <rect
            x="1071"
            y="169"
            rx="8"
            ry="8"
            width="65"
            height="15"
          />
          <rect
            x="625"
            y="169"
            rx="6"
            ry="6"
            width="97"
            height="11"
          />
          <rect
            x="1"
            y="0"
            rx="8"
            ry="8"
            width="415"
            height="16"
          />
          <rect
            x="1"
            y="56"
            rx="8"
            ry="8"
            width="50"
            height="16"
          />
          <rect
            x="0"
            y="88"
            rx="19"
            ry="19"
            width="775"
            height="37"
          />
          <rect
            x="1"
            y="169"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
          <rect
            x="1"
            y="266"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
          <rect
            x="0"
            y="361"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
          <rect
            x="0"
            y="458"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
          <rect
            x="0"
            y="554"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
          <rect
            x="96"
            y="169"
            rx="20"
            ry="20"
            width="472"
            height="464"
          />
          <rect
            x="625"
            y="440"
            rx="20"
            ry="20"
            width="263"
            height="48"
          />
          <rect
            x="623"
            y="518"
            rx="20"
            ry="20"
            width="321"
            height="86"
          />
          <rect
            x="623"
            y="718"
            rx="11"
            ry="11"
            width="126"
            height="22"
          />
          <rect
            x="1"
            y="718"
            rx="11"
            ry="11"
            width="126"
            height="22"
          />
          <rect
            x="0"
            y="792"
            rx="11"
            ry="11"
            width="235"
            height="22"
          />
          <rect
            x="625"
            y="781"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="625"
            y="814"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="625"
            y="844"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="623"
            y="872"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="623"
            y="901"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="625"
            y="931"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="625"
            y="781"
            rx="11"
            ry="11"
            width="511"
            height="22"
          />
          <rect
            x="1"
            y="834"
            rx="18"
            ry="18"
            width="562"
            height="35"
          />
          <rect
            x="1"
            y="877"
            rx="18"
            ry="18"
            width="562"
            height="35"
          />
          <rect
            x="1"
            y="922"
            rx="18"
            ry="18"
            width="562"
            height="35"
          />
          <rect
            x="895"
            y="440"
            rx="20"
            ry="20"
            width="49"
            height="49"
          />
          <rect
            x="0"
            y="361"
            rx="20"
            ry="20"
            width="79"
            height="79"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--tablet']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 640 1414"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="4"
            y="0"
            rx="8"
            ry="8"
            width="417"
            height="16"
          />
          <rect
            x="9"
            y="56"
            rx="8"
            ry="8"
            width="46"
            height="16"
          />
          <rect
            x="1"
            y="88"
            rx="15"
            ry="15"
            width="553"
            height="29"
          />
          <rect
            x="4"
            y="133"
            rx="15"
            ry="15"
            width="550"
            height="29"
          />
          <rect
            x="5"
            y="210"
            rx="10"
            ry="10"
            width="34"
            height="35"
          />
          <rect
            x="5"
            y="253"
            rx="10"
            ry="10"
            width="34"
            height="35"
          />
          <rect
            x="5"
            y="296"
            rx="10"
            ry="10"
            width="34"
            height="35"
          />
          <rect
            x="5"
            y="339"
            rx="10"
            ry="10"
            width="34"
            height="35"
          />
          <rect
            x="5"
            y="382"
            rx="10"
            ry="10"
            width="34"
            height="35"
          />
          <rect
            x="55"
            y="210"
            rx="10"
            ry="10"
            width="287"
            height="295"
          />
          <rect
            x="531"
            y="210"
            rx="8"
            ry="8"
            width="65"
            height="15"
          />
          <rect
            x="359"
            y="233"
            rx="16"
            ry="16"
            width="237"
            height="32"
          />
          <rect
            x="359"
            y="336"
            rx="16"
            ry="16"
            width="237"
            height="32"
          />
          <rect
            x="360"
            y="481"
            rx="20"
            ry="20"
            width="180"
            height="48"
          />
          <rect
            x="4"
            y="709"
            rx="12"
            ry="12"
            width="158"
            height="24"
          />
          <rect
            x="1"
            y="788"
            rx="12"
            ry="12"
            width="238"
            height="24"
          />
          <rect
            x="357"
            y="561"
            rx="6"
            ry="6"
            width="238"
            height="11"
          />
          <rect
            x="357"
            y="585"
            rx="6"
            ry="6"
            width="238"
            height="11"
          />
          <rect
            x="357"
            y="607"
            rx="6"
            ry="6"
            width="238"
            height="11"
          />
          <rect
            x="357"
            y="630"
            rx="6"
            ry="6"
            width="238"
            height="11"
          />
          <rect
            x="1"
            y="830"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="1"
            y="865"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="1"
            y="830"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="0"
            y="900"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="0"
            y="935"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="4"
            y="1020"
            rx="12"
            ry="12"
            width="158"
            height="24"
          />
          <rect
            x="1"
            y="1099"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="1"
            y="1141"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="1"
            y="1176"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="1"
            y="1141"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="0"
            y="1211"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="0"
            y="1246"
            rx="12"
            ry="12"
            width="595"
            height="24"
          />
          <rect
            x="359"
            y="428"
            rx="16"
            ry="16"
            width="132"
            height="31"
          />
          <rect
            x="548"
            y="481"
            rx="20"
            ry="20"
            width="48"
            height="48"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--mobile']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 288 1625"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="9"
            ry="9"
            width="279"
            height="17"
          />
          <rect
            x="0"
            y="72"
            rx="10"
            ry="10"
            width="279"
            height="27"
          />
          <rect
            x="1"
            y="107"
            rx="10"
            ry="10"
            width="279"
            height="27"
          />
          <rect
            x="0"
            y="166"
            rx="10"
            ry="10"
            width="288"
            height="288"
          />
          <rect
            x="1"
            y="470"
            rx="10"
            ry="10"
            width="50"
            height="50"
          />
          <rect
            x="1"
            y="557"
            rx="9"
            ry="9"
            width="105"
            height="17"
          />
          <rect
            x="0"
            y="661"
            rx="9"
            ry="9"
            width="105"
            height="17"
          />
          <rect
            x="1"
            y="583"
            rx="10"
            ry="10"
            width="287"
            height="31"
          />
          <rect
            x="1"
            y="682"
            rx="10"
            ry="10"
            width="287"
            height="35"
          />
          <rect
            x="1"
            y="773"
            rx="10"
            ry="10"
            width="131"
            height="35"
          />
          <rect
            x="0"
            y="830"
            rx="10"
            ry="10"
            width="231"
            height="48"
          />
          <rect
            x="1"
            y="910"
            rx="8"
            ry="8"
            width="287"
            height="15"
          />
          <rect
            x="1"
            y="933"
            rx="8"
            ry="8"
            width="287"
            height="15"
          />
          <rect
            x="1"
            y="956"
            rx="8"
            ry="8"
            width="287"
            height="15"
          />
          <rect
            x="1"
            y="979"
            rx="8"
            ry="8"
            width="287"
            height="15"
          />
          <rect
            x="240"
            y="830"
            rx="24"
            ry="24"
            width="48"
            height="48"
          />
          <rect
            x="183"
            y="559"
            rx="9"
            ry="9"
            width="105"
            height="17"
          />
          <rect
            x="60"
            y="470"
            rx="10"
            ry="10"
            width="50"
            height="50"
          />
          <rect
            x="119"
            y="470"
            rx="10"
            ry="10"
            width="50"
            height="50"
          />
          <rect
            x="179"
            y="470"
            rx="10"
            ry="10"
            width="50"
            height="50"
          />
          <rect
            x="237"
            y="470"
            rx="10"
            ry="10"
            width="50"
            height="50"
          />
          <rect
            x="0"
            y="41"
            rx="9"
            ry="9"
            width="64"
            height="17"
          />
        </ContentLoader>
      </div>
    </div>
  );
};

export default ProductInfoPageLoader;
