import ContentLoader from 'react-content-loader';
import style from './Loader.module.scss';

const CatalogPageLoader = () => {
  return (
    <div className={style.loader}>
      <div className={style['loader--desktop']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 1138 2481"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="1"
            y="56"
            rx="20"
            ry="20"
            width="360"
            height="41"
          />
          <rect
            x="0"
            y="200"
            rx="20"
            ry="20"
            width="177"
            height="41"
          />
          <rect
            x="192"
            y="200"
            rx="20"
            ry="20"
            width="129"
            height="41"
          />
          <rect
            x="0"
            y="181"
            rx="8"
            ry="8"
            width="49"
            height="15"
          />
          <rect
            x="192"
            y="181"
            rx="8"
            ry="8"
            width="97"
            height="15"
          />
          <rect
            x="0"
            y="120"
            rx="9"
            ry="9"
            width="72"
            height="17"
          />
          <rect
            x="1"
            y="0"
            rx="9"
            ry="9"
            width="96"
            height="17"
          />
          <rect
            x="1"
            y="264"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="1"
            y="810"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="5"
            y="1356"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="288"
            y="1355"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="581"
            y="1356"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="865"
            y="1356"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="1"
            y="1902"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="289"
            y="1901"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="577"
            y="1902"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="865"
            y="1901"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="443"
            y="2446"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="491"
            y="2446"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="531"
            y="2445"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="571"
            y="2446"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="615"
            y="2446"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="659"
            y="2446"
            rx="18"
            ry="18"
            width="35"
            height="35"
          />
          <rect
            x="288"
            y="809"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="581"
            y="810"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="865"
            y="810"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="289"
            y="264"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="577"
            y="264"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
          <rect
            x="865"
            y="263"
            rx="20"
            ry="20"
            width="272"
            height="506"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--tablet']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 592 1316"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="264"
            rx="20"
            ry="20"
            width="288"
            height="506"
          />
          <rect
            x="0"
            y="54"
            rx="20"
            ry="20"
            width="355"
            height="60"
          />
          <rect
            x="0"
            y="200"
            rx="20"
            ry="20"
            width="187"
            height="40"
          />
          <rect
            x="203"
            y="200"
            rx="20"
            ry="20"
            width="136"
            height="40"
          />
          <rect
            x="0"
            y="181"
            rx="8"
            ry="8"
            width="82"
            height="15"
          />
          <rect
            x="203"
            y="181"
            rx="8"
            ry="8"
            width="88"
            height="15"
          />
          <rect
            x="0"
            y="123"
            rx="8"
            ry="8"
            width="88"
            height="15"
          />
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="104"
            height="16"
          />
          <rect
            x="304"
            y="263"
            rx="20"
            ry="20"
            width="288"
            height="506"
          />
          <rect
            x="304"
            y="809"
            rx="20"
            ry="20"
            width="288"
            height="506"
          />
          <rect
            x="0"
            y="810"
            rx="20"
            ry="20"
            width="288"
            height="506"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--mobile']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 288 1625"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="40"
            rx="18"
            ry="18"
            width="237"
            height="36"
          />
          <rect
            x="0"
            y="161"
            rx="20"
            ry="20"
            width="136"
            height="40"
          />
          <rect
            x="1"
            y="225"
            rx="20"
            ry="20"
            width="287"
            height="440"
          />
          <rect
            x="1"
            y="705"
            rx="20"
            ry="20"
            width="287"
            height="440"
          />
          <rect
            x="1"
            y="1185"
            rx="20"
            ry="20"
            width="287"
            height="440"
          />
          <rect
            x="152"
            y="161"
            rx="20"
            ry="20"
            width="136"
            height="40"
          />
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="93"
            height="15"
          />
          <rect
            x="1"
            y="89"
            rx="8"
            ry="8"
            width="70"
            height="15"
          />
          <rect
            x="0"
            y="142"
            rx="8"
            ry="8"
            width="43"
            height="15"
          />
          <rect
            x="152"
            y="142"
            rx="8"
            ry="8"
            width="88"
            height="15"
          />
        </ContentLoader>
      </div>
    </div>
  );
};

export default CatalogPageLoader;
