import ContentLoader from 'react-content-loader';
import style from './Loader.module.scss';

const FavouritesPageLoader = () => {
  return (
    <div className={style.loader}>
      <div className={style['loader--desktop']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 1135 957"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="122"
            height="16"
          />
          <rect
            x="0"
            y="120"
            rx="8"
            ry="8"
            width="71"
            height="16"
          />
          <rect
            x="0"
            y="60"
            rx="19"
            ry="19"
            width="255"
            height="37"
          />
          <rect
            x="0"
            y="181"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="291"
            y="180"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="579"
            y="180"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="869"
            y="180"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="0"
            y="728"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="291"
            y="727"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="579"
            y="727"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
          <rect
            x="869"
            y="727"
            rx="20"
            ry="20"
            width="274"
            height="506"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--tablet']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 640 1414"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="130"
            height="15"
          />
          <rect
            x="0"
            y="119"
            rx="8"
            ry="8"
            width="130"
            height="15"
          />
          <rect
            x="0"
            y="180"
            rx="15"
            ry="15"
            width="288"
            height="506"
          />
          <rect
            x="0"
            y="726"
            rx="15"
            ry="15"
            width="288"
            height="506"
          />
          <rect
            x="304"
            y="726"
            rx="15"
            ry="15"
            width="288"
            height="506"
          />
          <rect
            x="301"
            y="179"
            rx="15"
            ry="15"
            width="288"
            height="506"
          />
          <rect
            x="0"
            y="60"
            rx="15"
            ry="15"
            width="373"
            height="38"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--mobile']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 288 1625"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="112"
            height="16"
          />
          <rect
            x="0"
            y="43"
            rx="10"
            ry="10"
            width="192"
            height="26"
          />
          <rect
            x="1"
            y="89"
            rx="7"
            ry="7"
            width="63"
            height="14"
          />
          <rect
            x="0"
            y="142"
            rx="10"
            ry="10"
            width="287"
            height="440"
          />
          <rect
            x="1"
            y="623"
            rx="10"
            ry="10"
            width="287"
            height="440"
          />
        </ContentLoader>
      </div>
    </div>
  );
};

export default FavouritesPageLoader;
