import ContentLoader from 'react-content-loader';
import style from './Loader.module.scss';

const CartPageLoader = () => {
  return (
    <div className={style.loader}>
      <div className={style['loader--desktop']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 1135 957"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="66"
            height="15"
          />
          <rect
            x="0"
            y="38"
            rx="19"
            ry="19"
            width="120"
            height="37"
          />
          <rect
            x="0"
            y="121"
            rx="20"
            ry="20"
            width="752"
            height="127"
          />
          <rect
            x="0"
            y="263"
            rx="20"
            ry="20"
            width="752"
            height="127"
          />
          <rect
            x="0"
            y="407"
            rx="20"
            ry="20"
            width="752"
            height="127"
          />
          <rect
            x="768"
            y="121"
            rx="20"
            ry="20"
            width="368"
            height="205"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--tablet']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 640 1414"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="0"
            rx="8"
            ry="8"
            width="55"
            height="15"
          />
          <rect
            x="0"
            y="36"
            rx="15"
            ry="15"
            width="118"
            height="39"
          />
          <rect
            x="0"
            y="120"
            rx="15"
            ry="15"
            width="592"
            height="128"
          />
          <rect
            x="0"
            y="265"
            rx="15"
            ry="15"
            width="592"
            height="128"
          />
          <rect
            x="0"
            y="408"
            rx="15"
            ry="15"
            width="592"
            height="128"
          />
          <rect
            x="0"
            y="568"
            rx="15"
            ry="15"
            width="592"
            height="190"
          />
        </ContentLoader>
      </div>
      <div className={style['loader--mobile']}>
        <ContentLoader
          speed={0.5}
          width="100%"
          height="100%"
          viewBox="0 0 288 1625"
          backgroundColor="#dfdfdf"
          foregroundColor="#ecebeb">
          <rect
            x="0"
            y="113"
            rx="15"
            ry="15"
            width="288"
            height="160"
          />
          <rect
            x="0"
            y="40"
            rx="15"
            ry="15"
            width="91"
            height="35"
          />
          <rect
            x="5"
            y="1"
            rx="8"
            ry="8"
            width="46"
            height="15"
          />
          <rect
            x="0"
            y="289"
            rx="15"
            ry="15"
            width="288"
            height="164"
          />
          <rect
            x="0"
            y="469"
            rx="15"
            ry="15"
            width="288"
            height="160"
          />
          <rect
            x="0"
            y="661"
            rx="15"
            ry="15"
            width="288"
            height="190"
          />
        </ContentLoader>
      </div>
    </div>
  );
};

export default CartPageLoader;
